baseURL = "http://blog.dcrichards.com/"
languageCode = "en-gb"
title = "DCRichards/blog"
theme = "default"
[markup]
  [markup.highlight]
    style = "github"
    [markup.goldmark]
      [markup.goldmark.extensions]
        footnote = true
